os: osx
osx_image: xcode11.4
language: objective-c

env:
  global:
  - DESTINATION="OS=13.2.2,name=iPhone 11 Pro"
  - WORKSPACE="Example.xcworkspace"
  - PROJECT="Example.xcodeproj"
  - EXAMPLE_SCHEME="Example"

stages:
  - Tests
  - Examples
  - Documentation

jobs:
  include:
  - stage: Tests
    name: "Unit Tests"
    language: objective-c
    cache: bundler
    env:
    - TEST_FRAMEWORK_SCHEME="TPPDF-Package"
    - PROJECT="TPPDF.xcodeproj"
    script:
    - swift package resolve
    - xcodebuild -project ${PROJECT}
                 -scheme ${TEST_FRAMEWORK_SCHEME}
                 -clonedSourcePackagesDirPath .
                 -derivedDataPath ${TRAVIS_BUILD_DIR}/derived_data
                 -sdk iphonesimulator
                 -destination "${DESTINATION}"
                 -configuration Debug
                 ONLY_ACTIVE_ARCH=YES
                 test | xcpretty

    after_success:
    - slather coverage -t --build-directory ${TRAVIS_BUILD_DIR}/derived_data --verb>
    - bash <(curl -s https://codecov.io/bash) -f cobertura.xml -X coveragepy -X gco>

  - stage: Examples
    name: "Example iOS - Cocoapods"
    language: objective-c
    env:
    - ROOT_FOLDER="Example iOS-Cocoapods"
    cache:
      bundler: true
      cocoapods: true
    podfile: "${ROOT_FOLDER}/Podfile"
    before_script:
    - bundle exec pod install --project-directory="${ROOT_FOLDER}"
    - cd "${ROOT_FOLDER}"
    script:
    - xcodebuild -workspace "$WORKSPACE"
                 -scheme "$EXAMPLE_SCHEME"
                 -sdk iphonesimulator
                 -destination "$DESTINATION"
                 -configuration Debug
                 -derivedDataPath ${TRAVIS_BUILD_DIR}/derived_data
                 ONLY_ACTIVE_ARCH=YES
                 build | xcpretty
    - cd ../
    - bundle exec pod lib lint --allow-warnings

  - stage: Examples
    name: "Example iOS - Carthage"
    language: objective-c
    env:
    - ROOT_FOLDER="Example iOS-Carthage"
    before_script:
    - cd "${ROOT_FOLDER}"
    - echo 'github "techprimate/TPPDF" "'$(git rev-parse HEAD)'"' > Cartfile
    - carthage update --platform ios --cache-builds
    script:
    - xcodebuild -workspace "$WORKSPACE"
                 -scheme "$EXAMPLE_SCHEME"
                 -sdk iphonesimulator
                 -destination "$DESTINATION"
                 -configuration Debug
                 -derivedDataPath ${TRAVIS_BUILD_DIR}/derived_data
                 ONLY_ACTIVE_ARCH=YES
                 build | xcpretty

  - stage: Examples
    name: "Example iOS - Swift PM"
    language: objective-c
    env:
    - ROOT_FOLDER="Example iOS-SwiftPM"
    script:
    - cd "${ROOT_FOLDER}"
    - xcodebuild -resolvePackageDependencies
                 -project ${PROJECT}
                 -scheme ${EXAMPLE_SCHEME}
                 -clonedSourcePackagesDirPath .
                 -derivedDataPath ${TRAVIS_BUILD_DIR}/derived_data
                 -configuration Debug | xcpretty
    - xcodebuild -project ${PROJECT}
                 -scheme ${EXAMPLE_SCHEME}
                 -clonedSourcePackagesDirPath .
                 -derivedDataPath ${TRAVIS_BUILD_DIR}/derived_data
                 -sdk iphonesimulator
                 -destination "${DESTINATION}"
                 -configuration Debug
                 ONLY_ACTIVE_ARCH=YES
                 build | xcpretty
    - xcodebuild -project ${PROJECT}
                 -scheme ${TEST_FRAMEWORK_SCHEME}
                 -clonedSourcePackagesDirPath .
                 -derivedDataPath ${TRAVIS_BUILD_DIR}/derived_data
                 -sdk iphonesimulator
                 -destination "${DESTINATION}"
                 -configuration Debug
                 ONLY_ACTIVE_ARCH=YES
                 test | xcpretty

  - stage: Documentation
    name: Generate Documentation
    language: objective-c
    if: branch = master
    cache: bundler
    script:
    - git remote update
    - git fetch origin gh-pages:gh-pages --depth 1
    - git checkout gh-pages
    - bundle exec jazzy
    - git add docs
    - git config user.name  "Travis"
    - git config user.email "jazzy@travis-ci.com"
    - git commit -m "Updated docs for $TRAVIS_TAG"
    - git remote add secure-origin https://${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
    - git push secure-origin gh-pages
