language: objective-c
osx_image: xcode9.1
podfile: Example/Podfile
env:
  global:
  - WORKSPACE=Example/TPPDF.xcworkspace
  - IOS_FRAMEWORK_SCHEME="TPPDF-Tests"
  - EXAMPLE_SCHEME="TPPDF-Example"
  matrix:
     - DESTINATION="OS=8.4,name=iPhone 6 Plus"
     - DESTINATION="OS=9.3,name=iPhone 6s Plus"
     - DESTINATION="OS=10.2,name=iPhone 7 Plus"
     - DESTINATION="OS=11.1,name=iPhone 8"
    
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild -workspace "$WORKSPACE" -scheme "$IOS_FRAMEWORK_SCHEME" -sdk iphonesimulator -destination "$DESTINATION" -configuration Debug   ONLY_ACTIVE_ARCH=YES -enableCodeCoverage YES build-for-testing test | xcpretty
  - xcodebuild -workspace "$WORKSPACE" -scheme "$IOS_FRAMEWORK_SCHEME" -sdk iphonesimulator -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=YES -enableCodeCoverage YES build-for-testing test | xcpretty
  - xcodebuild -workspace "$WORKSPACE" -scheme "$EXAMPLE_SCHEME"       -sdk iphonesimulator -destination "$DESTINATION" -configuration Debug   ONLY_ACTIVE_ARCH=YES build | xcpretty
  - pod lib lint
 
after_success:
  - bash <(curl -s https://codecov.io/bash) -cF ios
